name: flyksoft_ui
description: "A new Flutter package project."
version: 1.0.12+1
homepage: 'none'
publish_to: 'none'

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  flutter_svg: ^2.0.10+1
  top_snackbar_flutter: ^3.0.0+1
  core_feature:
    git:
      url: https://github.com/FlykSoft/flutter_core_feature.git
      ref: v1.0.4
  pagination_service:
    git:
      url: https://github.com/FlykSoft/flutter_pagination_service.git
      ref: v1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

